### ISSUE TITLE
"@party" can't use on Reforged 8.0.2

### ISSUE THREAD

**Issue by BlueSoar** [HHServers/PixelChat#1] opened 2020-07-10 10:43 UTC
https://paste.ubuntu.com/p/HnhZK3n8RV/
it can’t show party in pixelmon 8.0.2

**Comment by zbouvier** [comment] 2020-10-02 21:27
the issue is that it is sending null pokemon, If you have a full team it sends just fine.

**Comment by HHServers** [comment] 2020-12-06 13:41
I'll try and push an update out when I have some time

**Comment by HHServers** [comment] 2020-12-31 13:45
fixed in 5b8bbb144fd42ee3a1cedc38d4fd0c9ccf569bca

**Closed** 2020-12-31 13:45 UTC
